apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fastapi
  labels:
    app: fastapi
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: fastapi
    release: {{ .Release.Name }}